main: github.BTECompanion.BTECompanion
version: 2.0
api-version: 1.12.2
name: Oceania-PlotTerra
author: R3tuxn, Coppertine
depend: [HeadDatabase]

commands:
  creload:
    description: reload companion config
    usage: /creload
    permission: companion.creload
  createplot:
    description: create a new plot for the PlotSystem
    usage: /createplot
    permission: companion.createplot
  pasteplot:
    description: paste a plot
    usage: /pasteplot <ID>
    permission: companion.plot